<?php

namespace AppBundle\Repository;

/**
 * DishesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishesRepository extends \Doctrine\ORM\EntityRepository
{
}
