app:
    resource: '@AppBundle/Controller/'
    type: annotation

users:
    type: rest
    resource: "@AppBundle/Controller/api/UsersController.php"
    prefix:   api

dishes:
    type: rest
    resource: "@AppBundle/Controller/api/DishesController.php"
    prefix:   api