# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    images_uploader:
                class: AppBundle\Services\ImageUploader
                arguments: ['%upload_image_dir%']

    doctrine_images_listener:
            class: AppBundle\EventListener\ImageUploadListener
            arguments: ['@images_uploader']
            tags:
                - { name: doctrine.event_listener, event: prePersist }
